name: Issue to Pull Request
on:
  issues:
    types:
      - opened
      - edited
      - reopened
permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  validate:
    name: Validate .properties File and Create a submission Pull Request 
    # Only run this job if the issue has the 'new contribution' label
    if: contains(github.event.issue.labels.*.name, 'new contribution')
    runs-on: ubuntu-latest
    env:
      BRANCH_NAME: issue-${{ github.event.issue.number }}
      ISSUE_NUM: ${{ github.event.issue.number }}
      ISSUE_TITLE: ${{ github.event.issue.title }}
    steps:
      - name: Parse issue
        id: parseIssue
        uses: onmax/issue-form-parser@v1.5
        with:
          issue_number: ${{ github.event.issue.number }}

      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Read and validate properties txt file
        id: parseProps
        run: |
          python -u scripts/parse_and_validate_properties_txt.py \
            "${{ contains(github.event.issue.labels.*.name, 'library') && 'library' || 
                 contains(github.event.issue.labels.*.name, 'tools') && 'tool' ||
                 contains(github.event.issue.labels.*.name, 'mode') && 'mode' ||
                 contains(github.event.issue.labels.*.name, 'examples') && 'examples' }}" \
            "${{ fromJson(steps.parseIssue.outputs.payload)['Properties File URL'] }}"

      - name: add comment to issue
        id: issueComment
        if: success()
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Your properties file was successfully parsed.

      - name: if failure, add comment to issue
        if: failure()
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            There was an error in reading your properties file or parsing it.

            Please ensure that the URL is correct and the file follows the required format.

            ${{ steps.parseProps.outputs.error }}

      - name: check if target branch exists
        id: branchExists
        uses: GuillaumeFalourd/branch-exists@v1
        with:
          branch: ${{ env.BRANCH_NAME }}

      - name: delete target branch if exists
        if: steps.branchExists.outputs.exists == 'true'
        uses: dawidd6/action-delete-branch@v3
        with:
          github_token: ${{github.token}}
          branches: ${{ env.BRANCH_NAME }}

      - name: create branch
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh issue develop $ISSUE_NUM --name $BRANCH_NAME --checkout

      - name: edit database
        run: |
          cd scripts
          python add_new_contribution_to_yaml.py '${{ steps.parseProps.outputs.props }}'

      - name: commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: adding contribution ${{ github.event.issue.title }} from #${{ github.event.issue.number }}
          branch: ${{ env.BRANCH_NAME }}
          add_options: '-u'

      - name: Create pull request
        run: |
          gh pr create -B main -H $BRANCH_NAME --title "Adding ${{ github.event.issue.title }}" --body "This pull request will add ${{ github.event.issue.title }}
          
          and it closes \#${{ github.event.issue.number }}"
        env:
          GH_TOKEN: ${{ github.token }}

      - name: add comment to issue
        uses: peter-evans/create-or-update-comment@v4
        with:
          comment-id:  ${{ steps.issueComment.outputs.comment-id }}
          body: |
            A pull request with your contribution has been successfully created.


      - name: if failure, add comment to issue
        if: failure()
        uses: peter-evans/create-or-update-comment@v4
        with:
          comment-id:  ${{ steps.issueComment.outputs.comment-id }}
          body: |
            An error was encountered when adding your contribution.

            We will look into this issue as soon as possible. Please check the details of your submission and try again if necessary.